Web/ExamGenerator.Web/Areas/Administration/Controllers/SubjectController.cs
using ExamGenerator.Services.Data;
using ExamGenerator.Web.InputModels.Subject;
using ExamGenerator.Web.ViewModels.Subject;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace ExamGenerator.Web.Areas.Administration.Controllers
{
    public class SubjectController:AdministrationController
    {
        private readonly ISubjectService subjectService;

        public SubjectController(ISubjectService subjectService)
        {
            this.subjectService = subjectService;
        }

        public IActionResult Create() => View();

        [HttpPost]
        public async Task<IActionResult> Create(SubjectInputModel model)
        {
            if(!ModelState.IsValid)
            {
                return View(model);
            }
            await subjectService.Add(model);
            return RedirectToAction(nameof(GetAll));
        }

        public IActionResult Edit(int id)
        {
            SubjectEditModel subject = subjectService.GetById<SubjectEditModel>(id);
            return View(subject);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(SubjectEditModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            await subjectService.Update(model);

            return RedirectToAction("Index", "Home");
        }

        public IActionResult Delete(int id)
        {
            SubjectViewModel subject = subjectService.GetById<SubjectViewModel>(id);
            return View(subject);
        }

        [HttpPost]
        [ActionName(nameof(Delete))]
        public async Task<IActionResult> DeleteConfirm(int id)
        {
            await subjectService.Delete(id);
            return RedirectToAction("Index", "Home");
        }
       
        public async Task<IActionResult> GetAll()
        {
            return View(await subjectService.GetAll());
        }
    }
}

Web/ExamGenerator.Web/Controllers/SettingsController.cs
namespace ExamGenerator.Web.Controllers
{
    using System;
    using System.Linq;
    using System.Threading.Tasks;

    using ExamGenerator.Data.Common.Repositories;
    using ExamGenerator.Data.Models;
    using ExamGenerator.Services.Data;
    using ExamGenerator.Services.Mapping;
    using ExamGenerator.Web.ViewModels.Settings;

    using Microsoft.AspNetCore.Mvc;

    public class SettingsController : BaseController
    {
        private readonly ISettingsService settingsService;

        private readonly IDeletableEntityRepository<Setting> repository;

        public SettingsController(ISettingsService settingsService, IDeletableEntityRepository<Setting> repository)
        {
            this.settingsService = settingsService;
            this.repository = repository;
        }

        public IActionResult Index()
        {
            var settings = this.settingsService.GetAll<SettingViewModel>();
            var model = new SettingsListViewModel { Settings = settings };
            return this.View(model);
        }

        public async Task<IActionResult> InsertSetting()
        {
            var random = new Random();
            var setting = new Setting { Name = $"Name_{random.Next()}", Value = $"Value_{random.Next()}" };

            await this.repository.AddAsync(setting);
            await this.repository.SaveChangesAsync();

            return this.RedirectToAction(nameof(this.Index));
        }
    }
}

Web/ExamGenerator.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@this.ViewData["Title"] - ExamGenerator</title>

    <environment names="Development">
        <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" asp-append-version="true" />
        <link href="~/css/site.css" rel="stylesheet" asp-append-version="true" />
    </environment>
    <environment names="Staging,Production">
        <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" asp-append-version="true" />
        <link href="~/css/site.min.css" rel="stylesheet" asp-append-version="true" />
    </environment>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ExamGenerator</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Settings" asp-action="Index">Settings</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        @if (this.User.IsInRole(GlobalConstants.AdministratorRoleName))
                        {
                            <li class="dropdown">
                                <a class="nav-link dropdown-toggle text-dark" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Administration
                                </a>
                                <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                                    <a class="dropdown-item" asp-area="@GlobalConstants.AdministrationArea" asp-controller="Subject" asp-action="Create">Add subject</a>
                                    @*<div class="dropdown-divider"></div>*@
                                </div>
                            </li>
                        }
                        else if (User.Identity.IsAuthenticated)
                        {
                            @*<li class="nav-item">
                                    <a class="nav-link text-white" asp-controller="Feedback" asp-action="Send">Feedback</a>
                                </li>*@
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @this.RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.Year - ExamGenerator - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js" asp-append-version="true"></script>
        <script src="~/lib/popper.js/umd/popper.min.js" asp-append-version="true"></script>
        <script src="~/lib/jquery-validation/dist/jquery.validate.js" asp-append-version="true"></script>
        <script src="~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.js" asp-append-version="true"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js" asp-append-version="true"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="~/lib/jquery/dist/jquery.min.js" asp-append-version="true"></script>
        <script src="~/lib/jquery-validation/dist/jquery.validate.min.js" asp-append-version="true"></script>
        <script src="~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.js" asp-append-version="true"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.min.js" asp-append-version="true"></script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @this.RenderSection("Scripts", required: false)
</body>
</html>